DROP DATABASE IF EXISTS MSDS;
CREATE DATABASE msds;


DROP TABLE IF EXISTS MSDSCourseCatalog;

\c msds;


CREATE TABLE MSDSCourseCatalog(
    CID VARCHAR(100) NOT NULL,
    CNAME VARCHAR(100),
    CPREREQ VARCHAR(100)
);
