version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=master
    volumes:
      - ./postgres:/var/lib/postgresql/data/
      - ./post05:/mnt/psql_stuff
    networks:
      - psql
    ports:
      - "5433:5432"

volumes:
  postgres:

networks:
  psql:
    driver: bridge
